/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/company/CompanyPage': RouteRecordInfo<'/company/CompanyPage', '/company/CompanyPage', Record<never, never>, Record<never, never>>,
    '/company/EmployeePage': RouteRecordInfo<'/company/EmployeePage', '/company/EmployeePage', Record<never, never>, Record<never, never>>,
    '/employee/EmployeePage': RouteRecordInfo<'/employee/EmployeePage', '/employee/EmployeePage', Record<never, never>, Record<never, never>>,
    '/home/Home': RouteRecordInfo<'/home/Home', '/home/Home', Record<never, never>, Record<never, never>>,
  }
}
